//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.03 at 05:29:48 PM SAMT 
//


package com.example.barsa.xsd.ticket.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DoTicketOperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DoTicketOperationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="cudTicketOperation" type="{http://localhost:8899/Barsa/TM}CudTicketOperationType"/>
 *         &lt;element name="lifeTicketOperation" type="{http://localhost:8899/Barsa/TM}LifeTicketOperationType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoTicketOperationType", propOrder = {
    "cudTicketOperation",
    "lifeTicketOperation"
})
public class DoTicketOperationType {

    protected CudTicketOperationType cudTicketOperation;
    protected LifeTicketOperationType lifeTicketOperation;

    /**
     * Gets the value of the cudTicketOperation property.
     * 
     * @return
     *     possible object is
     *     {@link CudTicketOperationType }
     *     
     */
    public CudTicketOperationType getCudTicketOperation() {
        return cudTicketOperation;
    }

    /**
     * Sets the value of the cudTicketOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CudTicketOperationType }
     *     
     */
    public void setCudTicketOperation(CudTicketOperationType value) {
        this.cudTicketOperation = value;
    }

    /**
     * Gets the value of the lifeTicketOperation property.
     * 
     * @return
     *     possible object is
     *     {@link LifeTicketOperationType }
     *     
     */
    public LifeTicketOperationType getLifeTicketOperation() {
        return lifeTicketOperation;
    }

    /**
     * Sets the value of the lifeTicketOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeTicketOperationType }
     *     
     */
    public void setLifeTicketOperation(LifeTicketOperationType value) {
        this.lifeTicketOperation = value;
    }

}
