//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.03 at 05:29:48 PM SAMT 
//


package com.example.barsa.xsd.ticket.input;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.barsa.xsd.ticket.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.barsa.xsd.ticket.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DoTicketOperation }
     * 
     */
    public DoTicketOperation createDoTicketOperation() {
        return new DoTicketOperation();
    }

    /**
     * Create an instance of {@link ServiceInfoType }
     * 
     */
    public ServiceInfoType createServiceInfoType() {
        return new ServiceInfoType();
    }

    /**
     * Create an instance of {@link DoTicketOperationType }
     * 
     */
    public DoTicketOperationType createDoTicketOperationType() {
        return new DoTicketOperationType();
    }

    /**
     * Create an instance of {@link CudTicketOperationType }
     * 
     */
    public CudTicketOperationType createCudTicketOperationType() {
        return new CudTicketOperationType();
    }

    /**
     * Create an instance of {@link ProcessDataType }
     * 
     */
    public ProcessDataType createProcessDataType() {
        return new ProcessDataType();
    }

    /**
     * Create an instance of {@link LifeTicketOperationType }
     * 
     */
    public LifeTicketOperationType createLifeTicketOperationType() {
        return new LifeTicketOperationType();
    }

    /**
     * Create an instance of {@link UserInfo }
     * 
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

    /**
     * Create an instance of {@link TicketType }
     * 
     */
    public TicketType createTicketType() {
        return new TicketType();
    }

}
